<div style="text-align:justify">
    <h4><?= e($title) ?></h4>

    <h5>Angaben gemäß § 5 Telemediengesetz (TMG) sowie § 18 Medienstaatsvertrag (MStV)</h5>
    <P>Diese Website wird von einer Privatperson betrieben und verantwortet. Sie verfolgt ausschließlich private Zwecke. Aufgrund des Wortlautes der oben genannten Vorschriften ist der Betreiber dieser Website nicht verpflichtet ein Impressum anzubieten.</p>

    <p>Betreiber dieser Website ist Lars van Ravenzwaaij.</p>

    <p>Kontaktaufname ist möglich über das <a class="text-primary" href="https://www.ravenzwaaij.info/tree/ravenzwaaij/contact?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Ftree%2Fravenzwaaij">Kontaktformular</a>.</p>

    <h5>Haftung für Inhalte</h5>
    <p>Die Inhalte meiner Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte kann ich jedoch keine Gewähr übernehmen. Als Diensteanbieter bin ich gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG bin ich als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werde ich diese Inhalte umgehend entfernen.</p>

    <h5>Haftung für Links</h5>
    <p>Mein Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte ich keinen Einfluss habe. Deshalb kann ich für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werde ich derartige Links umgehend entfernen.</p>

    <h5>Urheberrecht</h5>
    <p>Die durch den Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werde ich derartige Inhalte umgehend entfernen.<p>

    <h5>Open Source</h5>
    <p>Diese website werd mittels <a class="text-primary" href="https://webtrees.net">webtrees</a>, eine Open-Source-Software, betrieben. Sie wird von Menschen aus vielen Ländern, unter den Bedingungen der GNU General Public License Verion 3 oder eine spätere Version, wie von der Free Software Foundation veröffentlicht, entwickelt. Die Entwickler stellen dem Projekt freiwillig ihre Zeit und ihre Talente zur Verfügung. Der gesamte Service, der Support und die zukünftige Entwicklung hängen von der Zeit ab, die die Entwickler bereit sind, für das Projekt zu spenden, oft auf Kosten von Arbeit, Freizeit und Familie. Abgesehen von den wenigen Spenden, die von den Benutzern eingehen, erhalten die Entwickler keine Entschädigung für die Zeit, die sie in das Projekt investieren. Es gibt auch keine externe Einnahmequelle zur Unterstützung des Projekts.</p>
</div>