<div style="text-align:justify">
    <h2><?= e($title) ?></h2>

    <h5>Information according to § 5 of the German Telemedia Act (TMG) and § 18 of the German State Media Treaty (MStV)</h5>
    <P>This website is operated by and is the responsibility of a private individual registered in Germany. It pursues exclusively private purposes without the intention of making a profit. Due to the wording of the above-mentioned regulations, the operator of the website is not obliged to provide a legal notice.</p>

    <p>Operator of the website is Lars van Ravenzwaaij.</p>

    <p>Contact is possible through the <a class="text-primary" href="https://www.ravenzwaaij.info/tree/ravenzwaaij/contact?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Ftree%2Fravenzwaaij">contactform</a>.</p>

    <h5>Purpose of the website</h5>
    <p>The private purpose of this website is to present the results of genealogical research on the operator's ancestors. The presentation is particularly aimed at Dutch-speaking visitors or persons with Dutch ancestors. The user interface is available in three languages: Dutch, English and German. The genealogical results are only available in Dutch.</p>

    <h5>Liability for contents</h5>
    <p>The contents of my pages have been created with the utmost care. However, I cannot assume any liability for the correctness, completeness and topicality of the contents. As a service provider, I am responsible for my own content on these pages in accordance with § 7 paragraph 1 of the German Telemedia Act (TMG). According to §§ 8 to 10 TMG, however, I am not obliged as a service provider to monitor transmitted or stored third-party information or to investigate circumstances that indicate illegal activity. Obligations to remove or block the use of information according to general laws remain unaffected by this. However, liability in this regard is only possible from the point in time at which a concrete infringement of the law becomes known. If I become aware of any such infringements, I will remove this content immediately.</p>

    <h5>Liability for links</h5>
    <p>My pages contain links to external websites of third parties, on whose contents I have no influence. Therefore, I cannot assume any liability for these external contents. The respective provider or operator of the pages is always responsible for the content of the linked pages. The linked pages were checked for possible legal violations at the time of linking. Illegal contents were not recognisable at the time of linking. However, permanent monitoring of the content of the linked pages is not reasonable without concrete indications of a legal violation. If I become aware of any infringements, I will remove such links immediately.</p>

    <h5>Copyright</h5>
    <p>The contents and works on these pages created by the site operator are subject to German copyright law. Duplication, processing, distribution and any kind of exploitation outside the limits of copyright require the written consent of the respective author or creator. Downloads and copies of this site are only permitted for private, non-commercial use. Insofar as the content on this site was not created by the operator, the copyrights of third parties are respected. In particular, third-party content is marked as such. Should you nevertheless become aware of a copyright infringement, please inform us accordingly. If I become aware of any infringements, I will remove such content immediately.<p>

    <h5>Open Source</h5>
    <p>This website is powered by <a class="text-primary" href="https://webtrees.net/webtrees">webtrees</a> - an open source software. It is developed by people from many countries, under the terms of the GNU General Public License Verion 3 or a later version as published by the Free Software Foundation. The developers volunteer their time and talents to the project. All service, support and future development depend on the time that developers are willing to donate to the project, often at the expense of work, free time and family. Apart from the few donations that come in from users, the developers receive no compensation for the time they invest in the project. There is also no external source of income to support the project.</p>
</div>