<div style="text-align:justify">
    <h2><?= e($title) ?></h2>

    <h5>Wettelijke informatie volgens § 5 van de Duitse telemediawet (TMG) en § 18 van het Duitse staatsmediabesluit (MStV)</h5>
    <P>Deze website wordt geëxploiteerd door en valt onder de verantwoordelijkheid van een, in Duitsland geregistreerde, particulier. Hij streeft uitsluitend privédoeleinden na zonder winstoogmerk. Op grond van de formulering van de bovengenoemde voorschriften is de beheerder van deze website niet verplicht een juridische kennísgeving te doen.</p>

    <p>Beheerder van deze website is Lars van Ravenzwaaij.</p>

    <p>Contactopname is mogelijk via het <a class="text-primary" href="https://www.ravenzwaaij.info/tree/ravenzwaaij/contact?to=Lars1963&url=https%3A%2F%2Fwww.ravenzwaaij.info%2Ftree%2Fravenzwaaij">contactformulier</a>.</p>

    <h5>Doel van de website</h5>
    <p>Het particuliere doel van deze website is het presenteren van de resultaten van het genealogisch onderzoek naar de voorouders van de beheerder. De presentatie is met name gericht op Nederlandstalige bezoekers of personen met Nederlandse voorouders. De gebruikersinterface is beschikbaar in drie talen: Nederlands, Engels en Duits. De genealogische resultaten zijn alleen beschikbaar in het Nederlands.</p>

    <h5>Aansprakelijkheid voor de inhoud</h5>
    <p>De inhoud van mijn pagina's is met de grootst mogelijke zorgvuldigheid samengesteld. Ik ben echter niet aansprakelijk voor de juistheid, volledigheid en actualiteit van de inhoud. Als dienstverlener ben ik volgens § 7 lid 1 van de Duitse Telemediawet (TMG) verantwoordelijk voor mijn eigen inhoud op deze pagina's. Volgens §§ 8 tot 10 TMG ben ik als dienstverlener echter niet verplicht doorgegeven of opgeslagen informatie van derden te controleren of omstandigheden te onderzoeken die wijzen op illegale activiteiten. Verplichtingen tot verwijdering of blokkering van het gebruik van informatie volgens de algemene wetten blijven hierdoor onaangetast. Aansprakelijkheid in dit verband is echter pas mogelijk vanaf het moment waarop een concrete inbreuk op de wet bekend wordt. Indien ik kennis neem van dergelijke inbreuken, zal ik deze inhoud onmiddellijk verwijderen..</p>

    <h5>Aansprakelijkheid voor links</h5>
    <p>Mijn pagina's bevatten links naar externe websites van derden, op de inhoud waarvan ik geen invloed heb. Daarom kan ik geen aansprakelijkheid aanvaarden voor deze externe inhoud. Voor de inhoud van de gelinkte pagina's is altijd de betreffende aanbieder of exploitant van de pagina's verantwoordelijk. De gelinkte pagina's werden op het moment van linken gecontroleerd op mogelijke wetsovertredingen. Illegale inhouden waren op het tijdstip van verlinken niet herkenbaar. Een permanente controle van de inhoud van de gelinkte pagina's is echter zonder concrete aanwijzingen van een wetsovertreding niet redelijk. Indien ik kennis neem van overtredingen, zal ik dergelijke links onmiddellijk verwijderen.</p>

    <h5>Copyright</h5>
    <p>De door de exploitant van de site gemaakte inhoud en werken op deze pagina's vallen onder het Duitse auteursrecht. Duplicatie, verwerking, verspreiding en elke vorm van exploitatie buiten de grenzen van het auteursrecht vereisen de schriftelijke toestemming van de betreffende auteur of maker. Downloads en kopieën van deze site zijn alleen toegestaan voor particulier, niet-commercieel gebruik. Voor zover de inhoud van deze site niet door de exploitant is gemaakt, worden de auteursrechten van derden gerespecteerd. In het bijzonder wordt de inhoud van derden als zodanig gekenmerkt. Mocht u desondanks een schending van het auteursrecht constateren, dan verzoeken wij u ons daarvan op de hoogte te stellen. Als ik kennis neem van inbreuken, zal ik deze inhoud onmiddellijk verwijderen.<p>

    <h5>Open Source</h5>
    <p>Deze website wordt aangedreven door <a class="text-primary" href="https://webtrees.net/webtrees">webtrees</a> - een open source software. Het is ontwikkeld door mensen uit vele landen, onder de voorwaarden van de GNU General Public License versie 3 of een latere versie zoals gepubliceerd door de Free Software Foundation. De ontwikkelaars zetten hun tijd en talenten vrijwillig in voor het project. Alle service, ondersteuning en toekomstige ontwikkeling hangen af van de tijd die de ontwikkelaars bereid zijn te doneren aan het project, vaak ten koste van werk, vrije tijd en familie. Behalve de weinige donaties van gebruikers ontvangen de ontwikkelaars geen vergoeding voor de tijd die zij in het project investeren. Er is ook geen externe bron van inkomsten om het project te ondersteunen.</p>
</div>